instrumentation:
    include-all-sources: true
    excludes: ['**/*.spec.js', 'spec/**/*.js']
reporting:
    reports:
        - lcov
    watermarks:
        statements: [60, 90]
        lines: [60, 90]
        functions: [60, 90]
        branches: [60, 90]
check:
    global:
        statements: 99
        lines: 99
        branches: 99
        functions: 99
    each:
        statements: 99
        lines: 99
        branches: 99
        functions: 99
